/**
 *
 * Copyright (c) 2023 C-NET
 * All rights reserved.
 * Created by XiangWei-Zeng
 *
 **/

/***
 * Auto Generate by esp - nn - case
*/


#ifndef MOBILEFACENET_OPT_HPP_ 
#define MOBILEFACENET_OPT_HPP_

#include "network.h"
#include "operation_define.h"

#define mobilefacenet_opt_blob__minusscalar0__minusscalar0 0
#define mobilefacenet_opt_blob__mulscalar0__mulscalar0 1
#define mobilefacenet_opt_blob__plus0__plus0 2
#define mobilefacenet_opt_blob__plus10__plus10 3
#define mobilefacenet_opt_blob__plus11__plus11 4
#define mobilefacenet_opt_blob__plus1__plus1 5
#define mobilefacenet_opt_blob__plus2__plus2 6
#define mobilefacenet_opt_blob__plus3__plus3 7
#define mobilefacenet_opt_blob__plus4__plus4 8
#define mobilefacenet_opt_blob__plus5__plus5 9
#define mobilefacenet_opt_blob__plus6__plus6 10
#define mobilefacenet_opt_blob__plus7__plus7 11
#define mobilefacenet_opt_blob__plus8__plus8 12
#define mobilefacenet_opt_blob__plus9__plus9 13
#define mobilefacenet_opt_blob_conv_1_conv2d_conv_1_batchnorm 14
#define mobilefacenet_opt_blob_conv_1_relu_conv_1_relu 15
#define mobilefacenet_opt_blob_conv_2_dw_conv2d_conv_2_dw_batchnorm 16
#define mobilefacenet_opt_blob_conv_2_dw_relu_conv_2_dw_relu 17
#define mobilefacenet_opt_blob_conv_6dw7_7_conv2d_conv_6dw7_7_batchnorm 18
#define mobilefacenet_opt_blob_conv_6sep_conv2d_conv_6sep_batchnorm 19
#define mobilefacenet_opt_blob_conv_6sep_relu_conv_6sep_relu 20
#define mobilefacenet_opt_blob_data_data 21
#define mobilefacenet_opt_blob_dconv_23_conv_dw_conv2d_dconv_23_conv_dw_batchnorm 22
#define mobilefacenet_opt_blob_dconv_23_conv_dw_relu_dconv_23_conv_dw_relu 23
#define mobilefacenet_opt_blob_dconv_23_conv_proj_conv2d_dconv_23_conv_proj_batchnorm 24
#define mobilefacenet_opt_blob_dconv_23_conv_sep_conv2d_dconv_23_conv_sep_batchnorm 25
#define mobilefacenet_opt_blob_dconv_23_conv_sep_relu_dconv_23_conv_sep_relu 26
#define mobilefacenet_opt_blob_dconv_34_conv_dw_conv2d_dconv_34_conv_dw_batchnorm 27
#define mobilefacenet_opt_blob_dconv_34_conv_dw_relu_dconv_34_conv_dw_relu 28
#define mobilefacenet_opt_blob_dconv_34_conv_proj_conv2d_dconv_34_conv_proj_batchnorm 29
#define mobilefacenet_opt_blob_dconv_34_conv_sep_conv2d_dconv_34_conv_sep_batchnorm 30
#define mobilefacenet_opt_blob_dconv_34_conv_sep_relu_dconv_34_conv_sep_relu 31
#define mobilefacenet_opt_blob_dconv_45_conv_dw_conv2d_dconv_45_conv_dw_batchnorm 32
#define mobilefacenet_opt_blob_dconv_45_conv_dw_relu_dconv_45_conv_dw_relu 33
#define mobilefacenet_opt_blob_dconv_45_conv_proj_conv2d_dconv_45_conv_proj_batchnorm 34
#define mobilefacenet_opt_blob_dconv_45_conv_sep_conv2d_dconv_45_conv_sep_batchnorm 35
#define mobilefacenet_opt_blob_dconv_45_conv_sep_relu_dconv_45_conv_sep_relu 36
#define mobilefacenet_opt_blob_pre_fc1_fc1 37
#define mobilefacenet_opt_blob_res_3_block0_conv_dw_conv2d_res_3_block0_conv_dw_batchnorm 38
#define mobilefacenet_opt_blob_res_3_block0_conv_dw_relu_res_3_block0_conv_dw_relu 39
#define mobilefacenet_opt_blob_res_3_block0_conv_proj_conv2d_res_3_block0_conv_proj_batchnorm 40
#define mobilefacenet_opt_blob_res_3_block0_conv_sep_conv2d_res_3_block0_conv_sep_batchnorm 41
#define mobilefacenet_opt_blob_res_3_block0_conv_sep_relu_res_3_block0_conv_sep_relu 42
#define mobilefacenet_opt_blob_res_3_block1_conv_dw_conv2d_res_3_block1_conv_dw_batchnorm 43
#define mobilefacenet_opt_blob_res_3_block1_conv_dw_relu_res_3_block1_conv_dw_relu 44
#define mobilefacenet_opt_blob_res_3_block1_conv_proj_conv2d_res_3_block1_conv_proj_batchnorm 45
#define mobilefacenet_opt_blob_res_3_block1_conv_sep_conv2d_res_3_block1_conv_sep_batchnorm 46
#define mobilefacenet_opt_blob_res_3_block1_conv_sep_relu_res_3_block1_conv_sep_relu 47
#define mobilefacenet_opt_blob_res_3_block2_conv_dw_conv2d_res_3_block2_conv_dw_batchnorm 48
#define mobilefacenet_opt_blob_res_3_block2_conv_dw_relu_res_3_block2_conv_dw_relu 49
#define mobilefacenet_opt_blob_res_3_block2_conv_proj_conv2d_res_3_block2_conv_proj_batchnorm 50
#define mobilefacenet_opt_blob_res_3_block2_conv_sep_conv2d_res_3_block2_conv_sep_batchnorm 51
#define mobilefacenet_opt_blob_res_3_block2_conv_sep_relu_res_3_block2_conv_sep_relu 52
#define mobilefacenet_opt_blob_res_3_block3_conv_dw_conv2d_res_3_block3_conv_dw_batchnorm 53
#define mobilefacenet_opt_blob_res_3_block3_conv_dw_relu_res_3_block3_conv_dw_relu 54
#define mobilefacenet_opt_blob_res_3_block3_conv_proj_conv2d_res_3_block3_conv_proj_batchnorm 55
#define mobilefacenet_opt_blob_res_3_block3_conv_sep_conv2d_res_3_block3_conv_sep_batchnorm 56
#define mobilefacenet_opt_blob_res_3_block3_conv_sep_relu_res_3_block3_conv_sep_relu 57
#define mobilefacenet_opt_blob_res_4_block0_conv_dw_conv2d_res_4_block0_conv_dw_batchnorm 58
#define mobilefacenet_opt_blob_res_4_block0_conv_dw_relu_res_4_block0_conv_dw_relu 59
#define mobilefacenet_opt_blob_res_4_block0_conv_proj_conv2d_res_4_block0_conv_proj_batchnorm 60
#define mobilefacenet_opt_blob_res_4_block0_conv_sep_conv2d_res_4_block0_conv_sep_batchnorm 61
#define mobilefacenet_opt_blob_res_4_block0_conv_sep_relu_res_4_block0_conv_sep_relu 62
#define mobilefacenet_opt_blob_res_4_block1_conv_dw_conv2d_res_4_block1_conv_dw_batchnorm 63
#define mobilefacenet_opt_blob_res_4_block1_conv_dw_relu_res_4_block1_conv_dw_relu 64
#define mobilefacenet_opt_blob_res_4_block1_conv_proj_conv2d_res_4_block1_conv_proj_batchnorm 65
#define mobilefacenet_opt_blob_res_4_block1_conv_sep_conv2d_res_4_block1_conv_sep_batchnorm 66
#define mobilefacenet_opt_blob_res_4_block1_conv_sep_relu_res_4_block1_conv_sep_relu 67
#define mobilefacenet_opt_blob_res_4_block2_conv_dw_conv2d_res_4_block2_conv_dw_batchnorm 68
#define mobilefacenet_opt_blob_res_4_block2_conv_dw_relu_res_4_block2_conv_dw_relu 69
#define mobilefacenet_opt_blob_res_4_block2_conv_proj_conv2d_res_4_block2_conv_proj_batchnorm 70
#define mobilefacenet_opt_blob_res_4_block2_conv_sep_conv2d_res_4_block2_conv_sep_batchnorm 71
#define mobilefacenet_opt_blob_res_4_block2_conv_sep_relu_res_4_block2_conv_sep_relu 72
#define mobilefacenet_opt_blob_res_4_block3_conv_dw_conv2d_res_4_block3_conv_dw_batchnorm 73
#define mobilefacenet_opt_blob_res_4_block3_conv_dw_relu_res_4_block3_conv_dw_relu 74
#define mobilefacenet_opt_blob_res_4_block3_conv_proj_conv2d_res_4_block3_conv_proj_batchnorm 75
#define mobilefacenet_opt_blob_res_4_block3_conv_sep_conv2d_res_4_block3_conv_sep_batchnorm 76
#define mobilefacenet_opt_blob_res_4_block3_conv_sep_relu_res_4_block3_conv_sep_relu 77
#define mobilefacenet_opt_blob_res_4_block4_conv_dw_conv2d_res_4_block4_conv_dw_batchnorm 78
#define mobilefacenet_opt_blob_res_4_block4_conv_dw_relu_res_4_block4_conv_dw_relu 79
#define mobilefacenet_opt_blob_res_4_block4_conv_proj_conv2d_res_4_block4_conv_proj_batchnorm 80
#define mobilefacenet_opt_blob_res_4_block4_conv_sep_conv2d_res_4_block4_conv_sep_batchnorm 81
#define mobilefacenet_opt_blob_res_4_block4_conv_sep_relu_res_4_block4_conv_sep_relu 82
#define mobilefacenet_opt_blob_res_4_block5_conv_dw_conv2d_res_4_block5_conv_dw_batchnorm 83
#define mobilefacenet_opt_blob_res_4_block5_conv_dw_relu_res_4_block5_conv_dw_relu 84
#define mobilefacenet_opt_blob_res_4_block5_conv_proj_conv2d_res_4_block5_conv_proj_batchnorm 85
#define mobilefacenet_opt_blob_res_4_block5_conv_sep_conv2d_res_4_block5_conv_sep_batchnorm 86
#define mobilefacenet_opt_blob_res_4_block5_conv_sep_relu_res_4_block5_conv_sep_relu 87
#define mobilefacenet_opt_blob_res_5_block0_conv_dw_conv2d_res_5_block0_conv_dw_batchnorm 88
#define mobilefacenet_opt_blob_res_5_block0_conv_dw_relu_res_5_block0_conv_dw_relu 89
#define mobilefacenet_opt_blob_res_5_block0_conv_proj_conv2d_res_5_block0_conv_proj_batchnorm 90
#define mobilefacenet_opt_blob_res_5_block0_conv_sep_conv2d_res_5_block0_conv_sep_batchnorm 91
#define mobilefacenet_opt_blob_res_5_block0_conv_sep_relu_res_5_block0_conv_sep_relu 92
#define mobilefacenet_opt_blob_res_5_block1_conv_dw_conv2d_res_5_block1_conv_dw_batchnorm 93
#define mobilefacenet_opt_blob_res_5_block1_conv_dw_relu_res_5_block1_conv_dw_relu 94
#define mobilefacenet_opt_blob_res_5_block1_conv_proj_conv2d_res_5_block1_conv_proj_batchnorm 95
#define mobilefacenet_opt_blob_res_5_block1_conv_sep_conv2d_res_5_block1_conv_sep_batchnorm 96
#define mobilefacenet_opt_blob_res_5_block1_conv_sep_relu_res_5_block1_conv_sep_relu 97

#define MOBILEFACENET_OPT_BLOB_SIZE 98

typedef struct mobilefacenet_opt_ncnn_blob{ const char *name; int blob_id;} mobilefacenet_opt_ncnn_blob_t;
static mobilefacenet_opt_ncnn_blob_t mobilefacenet_opt_ncnn_blobs [] = {
	{"data" , mobilefacenet_opt_blob_data_data},
	{"_minusscalar0" , mobilefacenet_opt_blob__minusscalar0__minusscalar0},
	{"_mulscalar0" , mobilefacenet_opt_blob__mulscalar0__mulscalar0},
	{"conv_1_batchnorm" , mobilefacenet_opt_blob_conv_1_conv2d_conv_1_batchnorm},
	{"conv_1_relu" , mobilefacenet_opt_blob_conv_1_relu_conv_1_relu},
	{"conv_2_dw_batchnorm" , mobilefacenet_opt_blob_conv_2_dw_conv2d_conv_2_dw_batchnorm},
	{"conv_2_dw_relu" , mobilefacenet_opt_blob_conv_2_dw_relu_conv_2_dw_relu},
	{"dconv_23_conv_sep_batchnorm" , mobilefacenet_opt_blob_dconv_23_conv_sep_conv2d_dconv_23_conv_sep_batchnorm},
	{"dconv_23_conv_sep_relu" , mobilefacenet_opt_blob_dconv_23_conv_sep_relu_dconv_23_conv_sep_relu},
	{"dconv_23_conv_dw_batchnorm" , mobilefacenet_opt_blob_dconv_23_conv_dw_conv2d_dconv_23_conv_dw_batchnorm},
	{"dconv_23_conv_dw_relu" , mobilefacenet_opt_blob_dconv_23_conv_dw_relu_dconv_23_conv_dw_relu},
	{"dconv_23_conv_proj_batchnorm" , mobilefacenet_opt_blob_dconv_23_conv_proj_conv2d_dconv_23_conv_proj_batchnorm},
	{"res_3_block0_conv_sep_batchnorm" , mobilefacenet_opt_blob_res_3_block0_conv_sep_conv2d_res_3_block0_conv_sep_batchnorm},
	{"res_3_block0_conv_sep_relu" , mobilefacenet_opt_blob_res_3_block0_conv_sep_relu_res_3_block0_conv_sep_relu},
	{"res_3_block0_conv_dw_batchnorm" , mobilefacenet_opt_blob_res_3_block0_conv_dw_conv2d_res_3_block0_conv_dw_batchnorm},
	{"res_3_block0_conv_dw_relu" , mobilefacenet_opt_blob_res_3_block0_conv_dw_relu_res_3_block0_conv_dw_relu},
	{"res_3_block0_conv_proj_batchnorm" , mobilefacenet_opt_blob_res_3_block0_conv_proj_conv2d_res_3_block0_conv_proj_batchnorm},
	{"_plus0" , mobilefacenet_opt_blob__plus0__plus0},
	{"res_3_block1_conv_sep_batchnorm" , mobilefacenet_opt_blob_res_3_block1_conv_sep_conv2d_res_3_block1_conv_sep_batchnorm},
	{"res_3_block1_conv_sep_relu" , mobilefacenet_opt_blob_res_3_block1_conv_sep_relu_res_3_block1_conv_sep_relu},
	{"res_3_block1_conv_dw_batchnorm" , mobilefacenet_opt_blob_res_3_block1_conv_dw_conv2d_res_3_block1_conv_dw_batchnorm},
	{"res_3_block1_conv_dw_relu" , mobilefacenet_opt_blob_res_3_block1_conv_dw_relu_res_3_block1_conv_dw_relu},
	{"res_3_block1_conv_proj_batchnorm" , mobilefacenet_opt_blob_res_3_block1_conv_proj_conv2d_res_3_block1_conv_proj_batchnorm},
	{"_plus1" , mobilefacenet_opt_blob__plus1__plus1},
	{"res_3_block2_conv_sep_batchnorm" , mobilefacenet_opt_blob_res_3_block2_conv_sep_conv2d_res_3_block2_conv_sep_batchnorm},
	{"res_3_block2_conv_sep_relu" , mobilefacenet_opt_blob_res_3_block2_conv_sep_relu_res_3_block2_conv_sep_relu},
	{"res_3_block2_conv_dw_batchnorm" , mobilefacenet_opt_blob_res_3_block2_conv_dw_conv2d_res_3_block2_conv_dw_batchnorm},
	{"res_3_block2_conv_dw_relu" , mobilefacenet_opt_blob_res_3_block2_conv_dw_relu_res_3_block2_conv_dw_relu},
	{"res_3_block2_conv_proj_batchnorm" , mobilefacenet_opt_blob_res_3_block2_conv_proj_conv2d_res_3_block2_conv_proj_batchnorm},
	{"_plus2" , mobilefacenet_opt_blob__plus2__plus2},
	{"res_3_block3_conv_sep_batchnorm" , mobilefacenet_opt_blob_res_3_block3_conv_sep_conv2d_res_3_block3_conv_sep_batchnorm},
	{"res_3_block3_conv_sep_relu" , mobilefacenet_opt_blob_res_3_block3_conv_sep_relu_res_3_block3_conv_sep_relu},
	{"res_3_block3_conv_dw_batchnorm" , mobilefacenet_opt_blob_res_3_block3_conv_dw_conv2d_res_3_block3_conv_dw_batchnorm},
	{"res_3_block3_conv_dw_relu" , mobilefacenet_opt_blob_res_3_block3_conv_dw_relu_res_3_block3_conv_dw_relu},
	{"res_3_block3_conv_proj_batchnorm" , mobilefacenet_opt_blob_res_3_block3_conv_proj_conv2d_res_3_block3_conv_proj_batchnorm},
	{"_plus3" , mobilefacenet_opt_blob__plus3__plus3},
	{"dconv_34_conv_sep_batchnorm" , mobilefacenet_opt_blob_dconv_34_conv_sep_conv2d_dconv_34_conv_sep_batchnorm},
	{"dconv_34_conv_sep_relu" , mobilefacenet_opt_blob_dconv_34_conv_sep_relu_dconv_34_conv_sep_relu},
	{"dconv_34_conv_dw_batchnorm" , mobilefacenet_opt_blob_dconv_34_conv_dw_conv2d_dconv_34_conv_dw_batchnorm},
	{"dconv_34_conv_dw_relu" , mobilefacenet_opt_blob_dconv_34_conv_dw_relu_dconv_34_conv_dw_relu},
	{"dconv_34_conv_proj_batchnorm" , mobilefacenet_opt_blob_dconv_34_conv_proj_conv2d_dconv_34_conv_proj_batchnorm},
	{"res_4_block0_conv_sep_batchnorm" , mobilefacenet_opt_blob_res_4_block0_conv_sep_conv2d_res_4_block0_conv_sep_batchnorm},
	{"res_4_block0_conv_sep_relu" , mobilefacenet_opt_blob_res_4_block0_conv_sep_relu_res_4_block0_conv_sep_relu},
	{"res_4_block0_conv_dw_batchnorm" , mobilefacenet_opt_blob_res_4_block0_conv_dw_conv2d_res_4_block0_conv_dw_batchnorm},
	{"res_4_block0_conv_dw_relu" , mobilefacenet_opt_blob_res_4_block0_conv_dw_relu_res_4_block0_conv_dw_relu},
	{"res_4_block0_conv_proj_batchnorm" , mobilefacenet_opt_blob_res_4_block0_conv_proj_conv2d_res_4_block0_conv_proj_batchnorm},
	{"_plus4" , mobilefacenet_opt_blob__plus4__plus4},
	{"res_4_block1_conv_sep_batchnorm" , mobilefacenet_opt_blob_res_4_block1_conv_sep_conv2d_res_4_block1_conv_sep_batchnorm},
	{"res_4_block1_conv_sep_relu" , mobilefacenet_opt_blob_res_4_block1_conv_sep_relu_res_4_block1_conv_sep_relu},
	{"res_4_block1_conv_dw_batchnorm" , mobilefacenet_opt_blob_res_4_block1_conv_dw_conv2d_res_4_block1_conv_dw_batchnorm},
	{"res_4_block1_conv_dw_relu" , mobilefacenet_opt_blob_res_4_block1_conv_dw_relu_res_4_block1_conv_dw_relu},
	{"res_4_block1_conv_proj_batchnorm" , mobilefacenet_opt_blob_res_4_block1_conv_proj_conv2d_res_4_block1_conv_proj_batchnorm},
	{"_plus5" , mobilefacenet_opt_blob__plus5__plus5},
	{"res_4_block2_conv_sep_batchnorm" , mobilefacenet_opt_blob_res_4_block2_conv_sep_conv2d_res_4_block2_conv_sep_batchnorm},
	{"res_4_block2_conv_sep_relu" , mobilefacenet_opt_blob_res_4_block2_conv_sep_relu_res_4_block2_conv_sep_relu},
	{"res_4_block2_conv_dw_batchnorm" , mobilefacenet_opt_blob_res_4_block2_conv_dw_conv2d_res_4_block2_conv_dw_batchnorm},
	{"res_4_block2_conv_dw_relu" , mobilefacenet_opt_blob_res_4_block2_conv_dw_relu_res_4_block2_conv_dw_relu},
	{"res_4_block2_conv_proj_batchnorm" , mobilefacenet_opt_blob_res_4_block2_conv_proj_conv2d_res_4_block2_conv_proj_batchnorm},
	{"_plus6" , mobilefacenet_opt_blob__plus6__plus6},
	{"res_4_block3_conv_sep_batchnorm" , mobilefacenet_opt_blob_res_4_block3_conv_sep_conv2d_res_4_block3_conv_sep_batchnorm},
	{"res_4_block3_conv_sep_relu" , mobilefacenet_opt_blob_res_4_block3_conv_sep_relu_res_4_block3_conv_sep_relu},
	{"res_4_block3_conv_dw_batchnorm" , mobilefacenet_opt_blob_res_4_block3_conv_dw_conv2d_res_4_block3_conv_dw_batchnorm},
	{"res_4_block3_conv_dw_relu" , mobilefacenet_opt_blob_res_4_block3_conv_dw_relu_res_4_block3_conv_dw_relu},
	{"res_4_block3_conv_proj_batchnorm" , mobilefacenet_opt_blob_res_4_block3_conv_proj_conv2d_res_4_block3_conv_proj_batchnorm},
	{"_plus7" , mobilefacenet_opt_blob__plus7__plus7},
	{"res_4_block4_conv_sep_batchnorm" , mobilefacenet_opt_blob_res_4_block4_conv_sep_conv2d_res_4_block4_conv_sep_batchnorm},
	{"res_4_block4_conv_sep_relu" , mobilefacenet_opt_blob_res_4_block4_conv_sep_relu_res_4_block4_conv_sep_relu},
	{"res_4_block4_conv_dw_batchnorm" , mobilefacenet_opt_blob_res_4_block4_conv_dw_conv2d_res_4_block4_conv_dw_batchnorm},
	{"res_4_block4_conv_dw_relu" , mobilefacenet_opt_blob_res_4_block4_conv_dw_relu_res_4_block4_conv_dw_relu},
	{"res_4_block4_conv_proj_batchnorm" , mobilefacenet_opt_blob_res_4_block4_conv_proj_conv2d_res_4_block4_conv_proj_batchnorm},
	{"_plus8" , mobilefacenet_opt_blob__plus8__plus8},
	{"res_4_block5_conv_sep_batchnorm" , mobilefacenet_opt_blob_res_4_block5_conv_sep_conv2d_res_4_block5_conv_sep_batchnorm},
	{"res_4_block5_conv_sep_relu" , mobilefacenet_opt_blob_res_4_block5_conv_sep_relu_res_4_block5_conv_sep_relu},
	{"res_4_block5_conv_dw_batchnorm" , mobilefacenet_opt_blob_res_4_block5_conv_dw_conv2d_res_4_block5_conv_dw_batchnorm},
	{"res_4_block5_conv_dw_relu" , mobilefacenet_opt_blob_res_4_block5_conv_dw_relu_res_4_block5_conv_dw_relu},
	{"res_4_block5_conv_proj_batchnorm" , mobilefacenet_opt_blob_res_4_block5_conv_proj_conv2d_res_4_block5_conv_proj_batchnorm},
	{"_plus9" , mobilefacenet_opt_blob__plus9__plus9},
	{"dconv_45_conv_sep_batchnorm" , mobilefacenet_opt_blob_dconv_45_conv_sep_conv2d_dconv_45_conv_sep_batchnorm},
	{"dconv_45_conv_sep_relu" , mobilefacenet_opt_blob_dconv_45_conv_sep_relu_dconv_45_conv_sep_relu},
	{"dconv_45_conv_dw_batchnorm" , mobilefacenet_opt_blob_dconv_45_conv_dw_conv2d_dconv_45_conv_dw_batchnorm},
	{"dconv_45_conv_dw_relu" , mobilefacenet_opt_blob_dconv_45_conv_dw_relu_dconv_45_conv_dw_relu},
	{"dconv_45_conv_proj_batchnorm" , mobilefacenet_opt_blob_dconv_45_conv_proj_conv2d_dconv_45_conv_proj_batchnorm},
	{"res_5_block0_conv_sep_batchnorm" , mobilefacenet_opt_blob_res_5_block0_conv_sep_conv2d_res_5_block0_conv_sep_batchnorm},
	{"res_5_block0_conv_sep_relu" , mobilefacenet_opt_blob_res_5_block0_conv_sep_relu_res_5_block0_conv_sep_relu},
	{"res_5_block0_conv_dw_batchnorm" , mobilefacenet_opt_blob_res_5_block0_conv_dw_conv2d_res_5_block0_conv_dw_batchnorm},
	{"res_5_block0_conv_dw_relu" , mobilefacenet_opt_blob_res_5_block0_conv_dw_relu_res_5_block0_conv_dw_relu},
	{"res_5_block0_conv_proj_batchnorm" , mobilefacenet_opt_blob_res_5_block0_conv_proj_conv2d_res_5_block0_conv_proj_batchnorm},
	{"_plus10" , mobilefacenet_opt_blob__plus10__plus10},
	{"res_5_block1_conv_sep_batchnorm" , mobilefacenet_opt_blob_res_5_block1_conv_sep_conv2d_res_5_block1_conv_sep_batchnorm},
	{"res_5_block1_conv_sep_relu" , mobilefacenet_opt_blob_res_5_block1_conv_sep_relu_res_5_block1_conv_sep_relu},
	{"res_5_block1_conv_dw_batchnorm" , mobilefacenet_opt_blob_res_5_block1_conv_dw_conv2d_res_5_block1_conv_dw_batchnorm},
	{"res_5_block1_conv_dw_relu" , mobilefacenet_opt_blob_res_5_block1_conv_dw_relu_res_5_block1_conv_dw_relu},
	{"res_5_block1_conv_proj_batchnorm" , mobilefacenet_opt_blob_res_5_block1_conv_proj_conv2d_res_5_block1_conv_proj_batchnorm},
	{"_plus11" , mobilefacenet_opt_blob__plus11__plus11},
	{"conv_6sep_batchnorm" , mobilefacenet_opt_blob_conv_6sep_conv2d_conv_6sep_batchnorm},
	{"conv_6sep_relu" , mobilefacenet_opt_blob_conv_6sep_relu_conv_6sep_relu},
	{"conv_6dw7_7_batchnorm" , mobilefacenet_opt_blob_conv_6dw7_7_conv2d_conv_6dw7_7_batchnorm},
	{"fc1" , mobilefacenet_opt_blob_pre_fc1_fc1},
};

extern network_t network_mobilefacenet_opt;

#endif//MOBILEFACENET_OPT
